### ISSUE TITLE
ViewEncapsulation

### ISSUE THREAD

**Issue by wenqi73** [wenqi73/Mat#7]
ViewEncapsulation是控制视图封装模式的API，它有三个属性：
```ts
enum ViewEncapsulation {
  Emulated: 0
  Native: 1
  None: 2
}
```
本文再用一个例子加深印象，三个组件按层级排序：

PersonComponent -> CompanyComponent -> AddressComponent

### Emulated
angular默认是Emulated模式，通过给DOM元素增加额外属性来模拟shadow DOM：
```html
<ng-component _nghost-c1>
  <h3 _ngcontent-c1>Person</h3>
  <p _ngcontent-c1>Welcome to Person Home</p>
  <app-company _ngcontent-c1 _nghost-c2>...</app-company>
</ng-component>
```

每个组件后面跟的属性_nghost-**都不一样，这样就把css局限在自己的组件视图中，而不影响其他的组件。

### Native
如果把company组件设置为Native模式，会发生怎样的变化？先看效果：

首先是两个`<h3>`的颜色没有了，它的样式在爷爷级组件person的css中：
```css
/* person.component.less */
:host /deep/ h3 {
    color: yellow;  
    font-style: italic;
}
```

Native模式是原生的shadow DOM模式，外面的样式进不来，里面的样式也出不去。这里把上级组件person中的样式阻隔了。

同理，下级组件address找不到自己的祖先元素：
```css
/* address.component.less */
:host-context(.my-theme) h3 {
    background-color: green;
    font-style: normal;
}

:host-context(.my-theme) p {
    color: red;
    font-size: 18px;
}
```

关于:host, :host-context, ::ng-deep的含义请看[https://angular.cn/guide/component-styles#特殊的选择器](https://angular.cn/guide/component-styles#特殊的选择器)

### None
none意味着放弃了shadow DOM和angular的保护，自己的class是对外敞开的，同时自身的css又能侵入到其他组件，与平时的css用法无异：

爷组件person的`<h3>`被侵入；company自身的边框没了，因为:host在普通css下已失效；要注意的是，孙组件address中的`<h3>`其实也被侵入，只是没能覆盖掉原来的样式。

### 子组件的样式
我们再给address组件加上h3的样式，同时去掉多余的样式，只观察company和address，并改变他们的ViewEncapsulation，看看结果会如何：

--- | --- | --- | --- | ---
--- | --- | --- | --- | ---
父 | None | None | Emulated | Emulated
子 | Emulated | None | Emulated | None
样式 | 子 | 子 | 子 | 子

四种情况，没有一种能够覆盖子组件的同名样式。Native的不用测了，它封闭的更严重。因此，要想改变子组件的样式，只能用:host ::ng-deep来达到目的：
```css
/* company.component.less */
:host ::ng-deep h3 {
    font-size: 15px;
    background-color: black;
} 
```

### 宿主元素的样式
我们也可以给宿主元素<app-company></app-company>加上class，利用@Component中host属性就可以：
```css
// address.component.ts
@Component({
  selector: 'app-address',
  encapsulation: ViewEncapsulation.None,
  template: `
          <h3>Address</h3>
          <p class="company">Welcome to Address Home</p>
  `,
  host: {
    '[class.address]': 'true'
  },
  styleUrls: ['./address.component.less']
})
```

这个的样式是可以被父组件控制的。

### ng-zorro
在ng-zorro中，所有的组件都加上了encapsulation: ViewEncapsulation.None，属于上面的第二或第四种情况。这就需要动用:host ::ng-deep了，不过也有一些地方是宿主元素本身（非子组件）的样式，直接写css覆盖即可。
